import { PrismaClient } from "@prisma/client";
import { WAVE1_HUBS } from "../src/lib/hubs";

// Destructive sample data. For curated hero CSVs use `npm run import:listings`
// (see docs/import-listings.md). Seed wipes listings; the importer upserts.

const prisma = new PrismaClient();

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=80`;

const hubHero: Record<string, string> = {
  houston: img("photo-1531218150217-54595bc2b934"),
  "dallas-fort-worth": img("photo-1541829070764-84a7d30dd3f3"),
  atlanta: img("photo-1570129477492-45c003edd2be"),
  tampa: img("photo-1506905925346-21bda4d32df4"),
  chicago: img("photo-1494522855154-9297acd4f30d"),
  charlotte: img("photo-1600585154340-be6161a56a0c"),
  austin: img("photo-1600596542815-ffad4c1539a9"),
  "st-louis": img("photo-1560518883-ce09059eeffa"),
  jacksonville: img("photo-1507525428034-b723cf961d3e"),
  orlando: img("photo-1506905925346-21bda4d32df4"),
  nashville: img("photo-1464146072230-91cddb340dcc"),
  memphis: img("photo-1486406146926-c627a92ad1ab"),
  birmingham: img("photo-1560518883-ce09059eeffa"),
  "oklahoma-city": img("photo-1541888946425-d81bb19240f5"),
  "greenville-sc": img("photo-1600585154340-be6161a56a0c"),
  raleigh: img("photo-1600596542815-ffad4c1539a9"),
  tulsa: img("photo-1504307651254-35680f356dfd"),
  "charleston-sc": img("photo-1507525428034-b723cf961d3e"),
  tallahassee: img("photo-1600585154340-be6161a56a0c"),
  pensacola: img("photo-1507525428034-b723cf961d3e"),
  "fort-myers": img("photo-1506905925346-21bda4d32df4"),
  sarasota: img("photo-1507525428034-b723cf961d3e"),
  "west-palm-beach": img("photo-1506905925346-21bda4d32df4"),
  "fort-lauderdale": img("photo-1507525428034-b723cf961d3e"),
  "daytona-beach": img("photo-1506905925346-21bda4d32df4"),
};

async function main() {
  await prisma.claimRequest.deleteMany();
  await prisma.submission.deleteMany();
  await prisma.listingCity.deleteMany();
  await prisma.listing.deleteMany();
  await prisma.city.deleteMany();

  const cities = await Promise.all(
    WAVE1_HUBS.map((hub, index) =>
      prisma.city.create({
        data: {
          slug: hub.slug,
          name: hub.name,
          state: hub.state,
          region: hub.region,
          sortOrder: index,
          description: hub.description,
          heroImage: hubHero[hub.slug],
        },
      }),
    ),
  );

  const bySlug = Object.fromEntries(cities.map((d) => [d.slug, d.id]));

  type Primary = "foundation" | "encapsulation" | "both";
  type Badge = "waterproofing" | "pier_beam" | "slab";

  type SeedListing = {
    slug: string;
    type: "contractor";
    name: string;
    tagline: string;
    bio: string;
    contactEmail: string;
    website: string;
    phone?: string;
    homeCity: string;
    homeState: string;
    licenseId?: string;
    photos: string[];
    primaryService: Primary;
    services: Badge[];
    featured: boolean;
    founding: boolean;
    verified: boolean;
    status: "published" | "draft";
    sourceUrl: string;
    claimable: boolean;
    claimedAt?: Date;
    citySlugs: string[];
  };

  const listings: SeedListing[] = [
    {
      slug: "gulf-coast-foundation-repair",
      type: "contractor",
      name: "Gulf Coast Foundation Repair",
      tagline: "Houston clay, steel piers, and a one-crew shop.",
      bio: "A Houston-based foundation shop that has worked the Energy Corridor, Bellaire, and the Bay for two decades. Steel-pier and slab programs, plus pier-and-beam releveling on older bungalows.",
      contactEmail: "elena@example.com",
      website: "https://example.com/gulf-coast-foundation",
      phone: "+1-713-555-0142",
      homeCity: "Houston",
      homeState: "TX",
      licenseId: "TX-FR-10422",
      photos: [img("photo-1504307651254-35680f356dfd"), img("photo-1541888946425-d81bb19240f5")],
      primaryService: "foundation",
      services: ["pier_beam", "slab"],
      featured: true,
      founding: true,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/gulf-coast-foundation",
      claimable: false,
      claimedAt: new Date("2024-11-02"),
      citySlugs: ["houston"],
    },
    {
      slug: "bayou-encapsulation-co",
      type: "contractor",
      name: "Bayou Encapsulation Co.",
      tagline: "Crawl-space envelopes for Houston humidity.",
      bio: "Bayou Encapsulation seals crawl spaces from the Heights to Sugar Land. Vapor barriers, sealed vents, and dehumidification. They partner with foundation shops when the joists need sistering first.",
      contactEmail: "bayou@example.com",
      website: "https://example.com/bayou-encapsulation",
      phone: "+1-281-555-0188",
      homeCity: "Houston",
      homeState: "TX",
      licenseId: "TX-EN-22190",
      photos: [img("photo-1590725175785-de025cc60835")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/bayou-encapsulation",
      claimable: true,
      citySlugs: ["houston"],
    },
    {
      slug: "cypress-pier-beam",
      type: "contractor",
      name: "Cypress Pier & Beam",
      tagline: "Northwest Houston — foundation and encapsulation.",
      bio: "A Cypress-based pair who specialize in pier-and-beam releveling and will encapsulate when the moisture load demands it. Primary flag is both.",
      contactEmail: "cypress@example.com",
      website: "https://example.com/cypress-pier-beam",
      homeCity: "Cypress",
      homeState: "TX",
      photos: [img("photo-1560518883-ce09059eeffa")],
      primaryService: "both",
      services: ["pier_beam"],
      featured: false,
      founding: false,
      verified: false,
      status: "published",
      sourceUrl: "https://example.com/cypress-pier-beam",
      claimable: true,
      citySlugs: ["houston"],
    },
    {
      slug: "north-texas-slab-pros",
      type: "contractor",
      name: "North Texas Slab Pros",
      tagline: "DFW post-tension and conventional slab repair.",
      bio: "North Texas Slab Pros works Plano, Frisco, and Fort Worth slabs — post-tension cable repair, void fill, and steel-pier lift programs.",
      contactEmail: "slab@example.com",
      website: "https://example.com/north-texas-slab",
      phone: "+1-214-555-0190",
      homeCity: "Plano",
      homeState: "TX",
      licenseId: "TX-FR-33011",
      photos: [img("photo-1541888946425-d81bb19240f5")],
      primaryService: "foundation",
      services: ["slab"],
      featured: true,
      founding: true,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/north-texas-slab",
      claimable: false,
      claimedAt: new Date("2025-03-14"),
      citySlugs: ["dallas-fort-worth"],
    },
    {
      slug: "metroplex-waterproofing",
      type: "contractor",
      name: "Metroplex Waterproofing",
      tagline: "Interior drains and crawl-space liners across DFW.",
      bio: "A Fort Worth–based encapsulation shop that also waterproofs. Interior drain tile, sump packages, and sealed crawl spaces.",
      contactEmail: "metroplex@example.com",
      website: "https://example.com/metroplex-waterproofing",
      homeCity: "Fort Worth",
      homeState: "TX",
      photos: [img("photo-1582407947304-fd86f028f716")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/metroplex-waterproofing",
      claimable: true,
      citySlugs: ["dallas-fort-worth"],
    },
    {
      slug: "peach-state-foundation",
      type: "contractor",
      name: "Peach State Foundation",
      tagline: "Atlanta clay — one inspection, one crew.",
      bio: "Peach State Foundation covers Metro Atlanta. Slab repair on the newer stock, crawl-space carpentry inside the perimeter, and an owner who still writes the proposal.",
      contactEmail: "atlanta@example.com",
      website: "https://example.com/peach-state-foundation",
      phone: "+1-404-555-0166",
      homeCity: "Atlanta",
      homeState: "GA",
      licenseId: "GA-CO-18804",
      photos: [img("photo-1504307651254-35680f356dfd")],
      primaryService: "foundation",
      services: ["slab"],
      featured: true,
      founding: true,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/peach-state-foundation",
      claimable: true,
      citySlugs: ["atlanta"],
    },
    {
      slug: "piedmont-encapsulation",
      type: "contractor",
      name: "Piedmont Encapsulation",
      tagline: "Atlanta crawl spaces, sealed and quiet.",
      bio: "A two-crew encapsulation shop that works north and east Atlanta. They waterproof a basement wall when the house has one; most of the book is crawl-space liners.",
      contactEmail: "piedmont@example.com",
      website: "https://example.com/piedmont-encap",
      homeCity: "Atlanta",
      homeState: "GA",
      photos: [img("photo-1590725175785-de025cc60835")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: false,
      status: "published",
      sourceUrl: "https://example.com/piedmont-encap",
      claimable: true,
      citySlugs: ["atlanta"],
    },
    {
      slug: "tampa-bay-foundation-co",
      type: "contractor",
      name: "Tampa Bay Foundation Co.",
      tagline: "Structural repair and encapsulation from Tampa to Clearwater.",
      bio: "Tampa Bay Foundation Co. lifts and stabilizes block and slab homes across the bay and encapsulates when the crawl space is the moisture source. Primary flag is both.",
      contactEmail: "tampa@example.com",
      website: "https://example.com/tampa-bay-foundation",
      phone: "+1-813-555-0177",
      homeCity: "Tampa",
      homeState: "FL",
      licenseId: "CBC-1258901",
      photos: [img("photo-1504307651254-35680f356dfd")],
      primaryService: "both",
      services: ["slab"],
      featured: true,
      founding: false,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/tampa-bay-foundation",
      claimable: false,
      claimedAt: new Date("2025-01-09"),
      citySlugs: ["tampa"],
    },
    {
      slug: "gulfshore-encapsulation",
      type: "contractor",
      name: "Gulfshore Encapsulation",
      tagline: "Tampa crawl-space envelopes.",
      bio: "Gulfshore seals crawl spaces on the bay side. High water tables, sandy soils, and a preference for closed envelopes with mechanical dehumidification.",
      contactEmail: "gulfshore@example.com",
      website: "https://example.com/gulfshore-encap",
      homeCity: "Tampa",
      homeState: "FL",
      photos: [img("photo-1590725175785-de025cc60835")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/gulfshore-encap",
      claimable: true,
      citySlugs: ["tampa"],
    },
    {
      slug: "lake-michigan-foundation",
      type: "contractor",
      name: "Lake Michigan Foundation",
      tagline: "Chicago masonry and clay — structural first.",
      bio: "Lake Michigan Foundation works Chicago and the near suburbs. Foundation repair on older masonry, steel piers where the soil allows, and an honest no when the house needs a different trade.",
      contactEmail: "chicago@example.com",
      website: "https://example.com/lake-michigan-foundation",
      homeCity: "Chicago",
      homeState: "IL",
      licenseId: "IL-GC-11844",
      photos: [img("photo-1494522855154-9297acd4f30d")],
      primaryService: "foundation",
      services: ["waterproofing"],
      featured: true,
      founding: true,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/lake-michigan-foundation",
      claimable: true,
      citySlugs: ["chicago"],
    },
    {
      slug: "chicago-crawl-space",
      type: "contractor",
      name: "Chicago Crawl Space Co.",
      tagline: "Encapsulation for bungalows and older stock.",
      bio: "A North Side encapsulation shop covering Chicago and the near-north suburbs. They waterproof when the wall is the leak; they encapsulate when the floor system is the sponge.",
      contactEmail: "ccc@example.com",
      website: "https://example.com/chicago-crawl",
      homeCity: "Chicago",
      homeState: "IL",
      photos: [img("photo-1600585154340-be6161a56a0c")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: false,
      status: "published",
      sourceUrl: "https://example.com/chicago-crawl",
      claimable: true,
      citySlugs: ["chicago"],
    },
    {
      slug: "queen-city-foundation",
      type: "contractor",
      name: "Queen City Foundation",
      tagline: "Charlotte clay and crawl-space carpentry.",
      bio: "Queen City Foundation relevels older Charlotte houses and will not sell a liner over a failing pier. Primary flag is foundation; encapsulation is referred out.",
      contactEmail: "charlotte@example.com",
      website: "https://example.com/queen-city-foundation",
      phone: "+1-704-555-0121",
      homeCity: "Charlotte",
      homeState: "NC",
      photos: [img("photo-1560518883-ce09059eeffa")],
      primaryService: "foundation",
      services: ["pier_beam"],
      featured: false,
      founding: false,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/queen-city-foundation",
      claimable: true,
      citySlugs: ["charlotte"],
    },
    {
      slug: "carolina-encapsulation",
      type: "contractor",
      name: "Carolina Encapsulation",
      tagline: "Charlotte crawl-space liners.",
      bio: "Carolina Encapsulation runs sealed envelopes and interior drains around Charlotte. They do not lift foundations; they keep water out of them.",
      contactEmail: "carolina@example.com",
      website: "https://example.com/carolina-encap",
      homeCity: "Charlotte",
      homeState: "NC",
      photos: [img("photo-1582407947304-fd86f028f716")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: false,
      status: "published",
      sourceUrl: "https://example.com/carolina-encap",
      claimable: true,
      citySlugs: ["charlotte"],
    },
    {
      slug: "hill-country-foundation",
      type: "contractor",
      name: "Hill Country Foundation",
      tagline: "Austin limestone and clay — foundation plus encapsulation.",
      bio: "Hill Country Foundation covers Austin and the western suburbs. Slab repair, pier-and-beam on the east side, and encapsulation when the crawl space is the moisture source.",
      contactEmail: "austin@example.com",
      website: "https://example.com/hill-country-foundation",
      phone: "+1-512-555-0166",
      homeCity: "Austin",
      homeState: "TX",
      licenseId: "TX-FR-18804",
      photos: [img("photo-1600596542815-ffad4c1539a9")],
      primaryService: "both",
      services: ["slab", "pier_beam"],
      featured: true,
      founding: false,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/hill-country-foundation",
      claimable: true,
      citySlugs: ["austin"],
    },
    {
      slug: "barton-creek-encapsulation",
      type: "contractor",
      name: "Barton Creek Encapsulation",
      tagline: "West Austin crawl spaces, sealed and quiet.",
      bio: "A two-crew encapsulation shop that works west and south Austin. They waterproof a basement wall when the house has one; most of the book is crawl-space liners.",
      contactEmail: "barton@example.com",
      website: "https://example.com/barton-creek-encap",
      homeCity: "Austin",
      homeState: "TX",
      photos: [img("photo-1590725175785-de025cc60835")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: false,
      status: "published",
      sourceUrl: "https://example.com/barton-creek-encap",
      claimable: true,
      citySlugs: ["austin"],
    },
    {
      slug: "gateway-foundation",
      type: "contractor",
      name: "Gateway Foundation",
      tagline: "St. Louis brick basements and clay.",
      bio: "Gateway Foundation works St. Louis city and county. Structural repair on brick and limestone, plus a waterproofing badge when the wall is the leak.",
      contactEmail: "gateway@example.com",
      website: "https://example.com/gateway-foundation",
      homeCity: "St. Louis",
      homeState: "MO",
      licenseId: "MO-FR-10933",
      photos: [img("photo-1503387762-592deb58ef4e")],
      primaryService: "foundation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/gateway-foundation",
      claimable: true,
      citySlugs: ["st-louis"],
    },
    {
      slug: "missouri-encapsulation",
      type: "contractor",
      name: "Missouri Encapsulation",
      tagline: "St. Louis crawl spaces and basements.",
      bio: "Missouri Encapsulation seals the rare St. Louis crawl space and the more common below-grade room. Humidity control is the product.",
      contactEmail: "missouri@example.com",
      website: "https://example.com/missouri-encap",
      homeCity: "St. Louis",
      homeState: "MO",
      photos: [img("photo-1590725175785-de025cc60835")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/missouri-encap",
      claimable: true,
      citySlugs: ["st-louis"],
    },
    {
      slug: "first-coast-encapsulation",
      type: "contractor",
      name: "First Coast Encapsulation",
      tagline: "Jacksonville crawl-space envelopes.",
      bio: "First Coast Encapsulation seals crawl spaces from the Beaches to Orange Park. Humidity and sandy soils; they encapsulate first and send foundation movement to a pier crew.",
      contactEmail: "firstcoast@example.com",
      website: "https://example.com/first-coast-encap",
      homeCity: "Jacksonville",
      homeState: "FL",
      photos: [img("photo-1590725175785-de025cc60835")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/first-coast-encap",
      claimable: true,
      citySlugs: ["jacksonville"],
    },
    {
      slug: "orange-blossom-crawl-seal",
      type: "contractor",
      name: "Orange Blossom Crawl Seal",
      tagline: "Orlando humidity, closed crawl envelopes.",
      bio: "Orange Blossom seals Central Florida crawl spaces. Vapor barriers, sealed vents, and dehumidifiers — encapsulation is the desk, not a waterproofing category page.",
      contactEmail: "orlando@example.com",
      website: "https://example.com/orange-blossom-encap",
      homeCity: "Orlando",
      homeState: "FL",
      photos: [img("photo-1590725175785-de025cc60835")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: false,
      status: "published",
      sourceUrl: "https://example.com/orange-blossom-encap",
      claimable: true,
      citySlugs: ["orlando"],
    },
    {
      slug: "cumberland-encapsulation",
      type: "contractor",
      name: "Cumberland Encapsulation",
      tagline: "Nashville crawl-space liners.",
      bio: "Cumberland Encapsulation works Nashville and the near counties. Musty crawls, humidity, and a liner-first desk. Foundation repair is referred when piers have already moved.",
      contactEmail: "cumberland@example.com",
      website: "https://example.com/cumberland-encap",
      homeCity: "Nashville",
      homeState: "TN",
      photos: [img("photo-1600585154340-be6161a56a0c")],
      primaryService: "encapsulation",
      services: ["waterproofing"],
      featured: false,
      founding: false,
      verified: true,
      status: "published",
      sourceUrl: "https://example.com/cumberland-encap",
      claimable: true,
      citySlugs: ["nashville"],
    },
    {
      slug: "lone-star-draft-works",
      type: "contractor",
      name: "Lone Star Draft Works",
      tagline: "Austin-side draft listing — awaiting photos and claim.",
      bio: "A placeholder contractor listing sourced from public materials. Awaiting operator claim, verified photos, and a current license id before it is featured.",
      contactEmail: "draft@example.com",
      website: "https://example.com/lone-star-draft",
      homeCity: "Austin",
      homeState: "TX",
      photos: [img("photo-1570129477492-45c003edd2be")],
      primaryService: "foundation",
      services: [],
      featured: false,
      founding: false,
      verified: false,
      status: "draft",
      sourceUrl: "https://example.com/lone-star-draft",
      claimable: true,
      citySlugs: ["austin"],
    },
  ];

  for (const listing of listings) {
    const { citySlugs, ...data } = listing;
    await prisma.listing.create({
      data: {
        ...data,
        cities: {
          create: citySlugs.map((slug) => ({
            cityId: bySlug[slug],
          })),
        },
      },
    });
  }

  console.log(`Seeded ${cities.length} city hubs and ${listings.length} listings.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
